services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    Helis\SettingsManagerBundle\Menu\MenuBuilder:
        arguments:
            - "@knp_menu.factory"
            - '@Helis\SettingsManagerBundle\Settings\EventManagerInterface'
        tags:
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: settings_manager_top_menu }
