name: CI

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: "PHPUnit"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
        symfony-version:
          - '6.4.*'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "${{ matrix.php-version }}"
          coverage: "${{ matrix.coverage }}"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"

      - name: "Run tests"
        run: composer run phpunit

  phpcs:
    runs-on: ubuntu-latest
    name: "PHPCSFixer"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "8.1"
          coverage: "none"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Check coding standard"
        run: composer run phpcs

  phpstan:
    runs-on: ubuntu-22.04
    name: "PHPStan"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Run static-analysis"
        run: composer run phpstan

  rector:
    runs-on: ubuntu-22.04
    name: "Rector"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Run static-analysis"
        run: composer run rector
