name: PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        version: 2
        php_version: 8.1
    - uses: php-actions/phpunit@v3
      with:
        php_version: 8.1
        memory_limit: 1G
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml.dist
