name: Rector

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.1
      - name: Run Rector
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.1
          command: rector
